config/routes.rb
Rails.application.routes.draw do
  resources :resumes
root to: "resumes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:Name, :DOB, :Email, :Address, :Phone, :Gender, :Qualification, :Experience, :Projects, :Hobbies, :LanguagesKnown, :School_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
<%= form_with(model: resume, local: true) do |form| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name, id: :resume_Name %>
  </div>

  <div class="field">
    <%= form.label :DOB %>
    <%= form.text_field :DOB, id: :resume_DOB %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email, id: :resume_Email %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_area :Address, id: :resume_Address %>
  </div>

  <div class="field">
    <%= form.label :Phone %>
    <%= form.text_field :Phone, id: :resume_Phone %>
  </div>

  <div class="field">
    <%= form.label :Gender %>
    <%= form.check_box :Gender, id: :resume_Gender %>
  </div>

  <div class="field">
    <%= form.label :Qualification %>
    <%= form.text_field :Qualification, id: :resume_Qualification %>
  </div>

  <div class="field">
    <%= form.label :Experience %>
    <%= form.text_field :Experience, id: :resume_Experience %>
  </div>

  <div class="field">
    <%= form.label :Projects %>
    <%= form.text_area :Projects, id: :resume_Projects %>
  </div>

  <div class="field">
    <%= form.label :Hobbies %>
    <%= form.text_field :Hobbies, id: :resume_Hobbies %>
  </div>

  <div class="field">
    <%= form.label :LanguagesKnown %>
    <%= form.text_area :LanguagesKnown, id: :resume_LanguagesKnown %>
  </div>

  <div class="field">
    <%= form.label :School_name %>
    <%= form.text_area :School_name, id: :resume_School_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Gender</th>
      <th>Qualification</th>
      <th>Experience</th>
      <th>Projects</th>
      <th>Hobbies</th>
      <th>Languagesknown</th>
      <th>School name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.Name %></td>
        <td><%= resume.DOB %></td>
        <td><%= resume.Email %></td>
        <td><%= resume.Address %></td>
        <td><%= resume.Phone %></td>
        <td><%= resume.Gender %></td>
        <td><%= resume.Qualification %></td>
        <td><%= resume.Experience %></td>
        <td><%= resume.Projects %></td>
        <td><%= resume.Hobbies %></td>
        <td><%= resume.LanguagesKnown %></td>
        <td><%= resume.School_name %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resume.Name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @resume.DOB %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.Email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @resume.Address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.Phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @resume.Gender %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @resume.Qualification %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @resume.Experience %>
</p>

<p>
  <strong>Projects:</strong>
  <%= @resume.Projects %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @resume.Hobbies %>
</p>

<p>
  <strong>Languagesknown:</strong>
  <%= @resume.LanguagesKnown %>
</p>

<p>
  <strong>School name:</strong>
  <%= @resume.School_name %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>